app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /{_locale}
    requirements:
        _locale: en|fr

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
