# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
          - { name: twig.extension}

    app.service.utils.arrayname:
        class: AppBundle\Service\Utils\ArrayNameService

    #bug à corriger
    app.service.utils.lastinsertidbdd:
        class: AppBundle\Service\Utils\LastInsertIdBDDService
        #arguments: ["@doctrine.orm.entity_manager"]

    app.service.upload:
        class: AppBundle\Service\UploadService
        arguments: ["@app.service.utils.arrayname", "%uploadDir%"]

    app.listener.product:
        class: AppBundle\Listener\ProductListener
        arguments: ["@app.service.upload", "@app.service.utils.lastinsertidbdd" ]
        tags:
          - { name: doctrine.orm.entity_listener }